const provinces=[['Hà Nội','Di sản — Thăng Long','north','red'],['Cao Bằng','Non nước — Biên cương','north','blue'],['Tuyên Quang','Cội nguồn — Núi rừng','north','teal'],['Điện Biên','Hào khí — Mường Thanh','north','purple'],['Lai Châu','Mây núi — Sắc chàm','north','blue'],['Sơn La','Ban trắng — Cao nguyên','north','gold'],['Lào Cai','Đỉnh cao — Fansipan','north','red'],['Thái Nguyên','Đệ nhất danh trà','north','teal'],['Lạng Sơn','Kỳ vĩ — Mẫu Sơn','north','purple'],['Quảng Ninh','Di sản — Vịnh Rồng','north','blue'],['Bắc Ninh','Quan họ — Kinh Bắc','north','red'],['Phú Thọ','Đất Tổ — Hùng Vương','north','gold'],['Hải Phòng','Sóng đỏ — Cảng biển','north','red'],['Hưng Yên','Phố Hiến — Nhãn lồng','north','orange'],['Ninh Bình','Non nước — Tràng An','north','teal'],['Thanh Hóa','Địa linh — Lam Sơn','central','blue'],['Nghệ An','Ví giặm — Gió Lào','central','gold'],['Hà Tĩnh','Hồng Lĩnh — Biển Đông','central','red'],['Quảng Trị','Khát vọng — Vĩ tuyến','central','orange'],['Huế','Di sản — Kinh kỳ','central','purple'],['Đà Nẵng','Chuyển động — Biển xanh','central','blue'],['Quảng Ngãi','Núi Ấn — Sông Trà','central','teal'],['Gia Lai','Đại ngàn — Cao nguyên','central','gold'],['Khánh Hòa','Trầm hương — Biển đảo','central','blue'],['Đắk Lắk','Sử thi — Đại ngàn','central','red'],['Lâm Đồng','Sương phố — Cao nguyên','central','teal'],['Đồng Nai','Hợp lưu — Công nghiệp','south','orange'],['TP. Hồ Chí Minh','Thành phố không ngủ','south','red'],['Tây Ninh','Núi Bà — Ánh dương','south','gold'],['Cần Thơ','Tây Đô — Sông nước','south','purple'],['Vĩnh Long','Phù sa — Miệt vườn','south','orange'],['Đồng Tháp','Sen hồng — Đất lành','south','red'],['An Giang','Thất Sơn — Hùng vĩ','south','teal'],['Cà Mau','Cực Nam — Đất Mũi','south','teal']];
const grid=document.querySelector('#provinceGrid');const palette=['#efd7d4','#d8e0e6','#d7e3dc','#e3d8e8','#eadfc8'];grid.innerHTML=provinces.map((p,i)=>`<article class="card" data-name="${p[0].toLowerCase()}" data-region="${p[2]}" style="--card-bg:${palette[i%palette.length]}"><span class="card-num">${String(i+1).padStart(2,'0')} / 34</span><div class="jersey ${p[3]}"><span>VN / 34</span><b>${String(i+1).padStart(2,'0')}</b></div><h3>${p[0]}</h3><p>${p[1]}</p><a href="#featured" aria-label="Xem ${p[0]}">→</a></article>`).join('');
let active='all';const search=document.querySelector('#search'),count=document.querySelector('#resultCount');function filter(){let n=0,q=search.value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');document.querySelectorAll('.card').forEach(c=>{let name=c.dataset.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'');let show=(active==='all'||c.dataset.region===active)&&name.includes(q);c.classList.toggle('hidden',!show);if(show)n++});count.textContent=`${n} thiết kế`}search.addEventListener('input',filter);document.querySelector('#filterBtns').addEventListener('click',e=>{if(!e.target.dataset.filter)return;active=e.target.dataset.filter;document.querySelectorAll('#filterBtns button').forEach(b=>b.classList.toggle('active',b===e.target));filter()});document.querySelector('#loadMore').onclick=e=>{grid.classList.add('show-all');e.currentTarget.remove()};
document.querySelector('#jerseyRail').innerHTML=provinces.slice(0,12).map((p,i)=>`<article class="rail-item"><div class="jersey ${p[3]}"><span>VN / 34</span><b>${String(i+1).padStart(2,'0')}</b></div><h3>${p[0]}</h3></article>`).join('');
const points=[[150,45],[190,100],[130,140],[165,190],[150,250],[175,310],[142,380],[170,455],[140,525],[165,615]];document.querySelector('#mapPoints').innerHTML=points.map((p,i)=>`<circle class="map-dot ${i===0?'active':''}" cx="${p[0]}" cy="${p[1]}" r="6" data-i="${[3,1,9,15,19,20,22,24,27,33][i]}"/>`).join('');document.querySelector('.vn-map').onclick=e=>{if(!e.target.dataset.i)return;document.querySelectorAll('.map-dot').forEach(d=>d.classList.remove('active'));e.target.classList.add('active');let i=+e.target.dataset.i,p=provinces[i],f=document.querySelector('#provinceFocus');f.querySelector('.focus-num').textContent=`${String(i+1).padStart(2,'0')} / 34`;f.querySelector('h3').textContent=p[0];f.querySelector('.eyebrow').textContent=p[1];f.querySelector('.mini-jersey').className=`mini-jersey ${p[3]}`;f.querySelector('.mini-jersey b').textContent=String(i+1).padStart(2,'0')};
addEventListener('scroll',()=>document.querySelector('#nav').classList.toggle('scrolled',scrollY>40));const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const ni=document.querySelector('#nameInput'),nu=document.querySelector('#numInput');ni.oninput=()=>document.querySelector('#mockName').textContent=ni.value||'QUÊ HƯƠNG';nu.oninput=()=>document.querySelector('#mockNum').textContent=nu.value||'34';

// Premium campaign opening: staged reveal, ambient motion and province ticker.
const hero=document.querySelector('.hero');hero.classList.add('hero-special');hero.querySelector('.hero-copy').classList.remove('reveal');
document.body.insertAdjacentHTML('afterbegin','<div class="opening" aria-hidden="true"><div class="opening-mark"><span>VN</span><i>/ 34</i></div><div class="opening-line"></div><p>PROVINCE FOOTBALL COLLECTION · 2026</p></div>');
hero.querySelector('.hero-bg').insertAdjacentHTML('afterend','<div class="hero-beam beam-a"></div><div class="hero-beam beam-b"></div><div class="hero-map" aria-hidden="true">VIỆT<br>NAM</div>');
hero.querySelector('.eyebrow').outerHTML='<div class="hero-kicker"><span>01</span><p>VIETNAM PROVINCE<br>COLLECTION / 2026</p></div>';
hero.querySelectorAll('h1 span,h1 em').forEach(line=>line.innerHTML='<i>'+line.innerHTML+'</i>');
hero.querySelector('.btn').classList.add('hero-btn');hero.querySelector('.hero-code').innerHTML='<span>VN / 34</span><br><small>10°–23° N · 102°–110° E</small>';
hero.insertAdjacentHTML('beforeend','<div class="hero-index"><b>34</b><span>VÙNG ĐẤT<br>01 TINH THẦN</span></div><div class="province-ticker"><div>HÀ NỘI · CAO BẰNG · TUYÊN QUANG · ĐIỆN BIÊN · LÀO CAI · QUẢNG NINH · HUẾ · ĐÀ NẴNG · GIA LAI · KHÁNH HÒA · TP. HỒ CHÍ MINH · CÀ MAU ·&nbsp;</div><div aria-hidden="true">HÀ NỘI · CAO BẰNG · TUYÊN QUANG · ĐIỆN BIÊN · LÀO CAI · QUẢNG NINH · HUẾ · ĐÀ NẴNG · GIA LAI · KHÁNH HÒA · TP. HỒ CHÍ MINH · CÀ MAU ·&nbsp;</div></div><div class="cursor-glow"></div>');
const glow=document.querySelector('.cursor-glow');hero.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});hero.addEventListener('pointerleave',()=>glow.style.opacity=0);hero.addEventListener('pointerenter',()=>glow.style.opacity=1);

// Interactive journey progress and product-card spotlight.
document.body.insertAdjacentHTML('afterbegin','<div class="journey-progress" aria-hidden="true"><i></i></div>');
const progressBar=document.querySelector('.journey-progress i');addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progressBar.style.width=(max?scrollY/max*100:0)+'%'},{passive:true});
document.querySelectorAll('.card').forEach(card=>card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--mx',(e.clientX-r.left)+'px');card.style.setProperty('--my',(e.clientY-r.top)+'px')}));

// Province personality matcher.
document.body.insertAdjacentHTML('beforeend',`<button class="discover-fab" aria-label="Tìm màu áo hợp với bạn">TÌM MÀU ÁO<br>CỦA BẠN</button><div class="match-modal" role="dialog" aria-modal="true" aria-label="Tìm màu áo của bạn"><div class="match-panel"><button class="match-close" aria-label="Đóng">×</button><div class="match-art"><div class="jersey red"><span>VN / 34</span><b>?</b></div></div><div class="match-content"><section class="match-step active" data-step="1"><span class="match-count">01 / 02</span><h3>BẠN THUỘC<br>VỀ VÙNG NÀO?</h3><div class="match-options"><button data-region="north">MIỀN BẮC<br>Di sản & khí chất</button><button data-region="central">MIỀN TRUNG<br>Bền bỉ & tự do</button><button data-region="south">MIỀN NAM<br>Phóng khoáng & năng động</button><button data-region="all">KHẮP VIỆT NAM<br>Để cảm xúc lựa chọn</button></div></section><section class="match-step" data-step="2"><span class="match-count">02 / 02</span><h3>NĂNG LƯỢNG<br>CỦA BẠN?</h3><div class="match-options"><button data-vibe="bold">MẠNH MẼ</button><button data-vibe="calm">TINH TẾ</button><button data-vibe="explore">KHÁM PHÁ</button><button data-vibe="proud">TỰ HÀO</button></div></section><section class="match-step match-result" data-step="3"><span class="match-count">YOUR MATCH / VN 34</span><h3 class="result-province">HÀ NỘI</h3><p class="result-story"></p><div class="result-actions"><a class="btn result-view" href="#collection">XEM MÀU ÁO →</a><button class="match-again">CHỌN LẠI</button></div></section></div></div></div>`);
const modal=document.querySelector('.match-modal'),fab=document.querySelector('.discover-fab'),matchJersey=modal.querySelector('.jersey');let chosenRegion='all';const setMatchStep=n=>modal.querySelectorAll('.match-step').forEach(s=>s.classList.toggle('active',s.dataset.step==n));fab.onclick=()=>{modal.classList.add('open');document.body.style.overflow='hidden'};const closeMatch=()=>{modal.classList.remove('open');document.body.style.overflow=''};modal.querySelector('.match-close').onclick=closeMatch;modal.addEventListener('click',e=>{if(e.target===modal)closeMatch()});addEventListener('keydown',e=>{if(e.key==='Escape')closeMatch()});
modal.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{chosenRegion=b.dataset.region;setMatchStep(2)});modal.querySelectorAll('[data-vibe]').forEach(b=>b.onclick=()=>{let pool=chosenRegion==='all'?provinces:provinces.filter(p=>p[2]===chosenRegion),salt={bold:3,calm:7,explore:11,proud:17}[b.dataset.vibe],pick=pool[(new Date().getDate()+salt)%pool.length],idx=provinces.indexOf(pick);modal.querySelector('.result-province').textContent=pick[0];modal.querySelector('.result-story').textContent=pick[1]+' — một thiết kế dành cho tinh thần '+b.textContent.toLowerCase()+'.';matchJersey.className='jersey '+pick[3];matchJersey.querySelector('b').textContent=String(idx+1).padStart(2,'0');setMatchStep(3);modal.querySelector('.result-view').onclick=()=>{closeMatch();setTimeout(()=>{const card=document.querySelectorAll('.card')[idx];grid.classList.add('show-all');card.scrollIntoView({behavior:'smooth',block:'center'});card.classList.add('card-flash');setTimeout(()=>card.classList.remove('card-flash'),1000)},250)}});modal.querySelector('.match-again').onclick=()=>{setMatchStep(1);matchJersey.className='jersey red';matchJersey.querySelector('b').textContent='?'};

// One-click serendipity above the collection grid.
document.querySelector('.collection-title').insertAdjacentHTML('beforeend','<button class="surprise-btn">↻ TỈNH THÀNH BẤT NGỜ</button>');document.querySelector('.surprise-btn').onclick=()=>{grid.classList.add('show-all');const cards=[...document.querySelectorAll('.card')],card=cards[Math.floor(Math.random()*cards.length)];card.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{card.classList.add('card-flash');setTimeout(()=>card.classList.remove('card-flash'),1000)},500)};
